config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destory]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
  end

  def show; end

  def edit; end

  def update
    @article.update(article_params)
    redirect_to articles_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <div class="mb-3">
    <%= f.label :title, "title" %>
    <%= f.text_field :title %>
    <div class="mb-3">
      <%= f.label :content, "content" %>
      <%= f.text_field :content %>
      <div class="mb-3">
        <%= f.submit %>
      <% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<br>
<% @articles.each do |article| %>
  <div>
    <ul>
      <li>
        <%= link_to article.title, article_path(article) %>
        <%= article.content %>
      <% end %>
    </li>
  </ul>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render "form", article: @article %>
<br>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<br>
<h1><%= @article.title %></h1>
<h3><%= @article.content %></h3>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="card">
      <h2><%= link_to "Wikinimous", articles_path %></h2>
      <%= link_to 'New article', new_article_path %>
    </div>
    <%= yield %>
  </body>
</html>